- contact.html
- index.html
- style.css
I have added the contact page 
Check it
Thank you
> add contact page

- index.html
- login-sginup.html
#26 Description: This pull request adds links to the login and signup pages in the navigation bar, making it easier for users to access authentication features. The links are designed to be responsive and fit seamlessly into the existing navigation structure.
Key Changes:
Added "Login" and "Signup" links to the navigation bar.
Ensured responsiveness across different screen sizes (mobile, tablet, desktop).
Styled the links to match the overall theme of the website.
Verified that the links point to the correct login and signup routes.
Testing:
Manually tested across multiple devices to confirm responsiveness.
Checked that both links direct to the correct authentication pages.
> Add link to login/signup page in navigation

- index.html
- style.css
**Issue No**:#5
**Changes Done :**
1. Added Flex Column
2. Alignment Fixed
3. Input Type Changed From text to email
4. Added Placeholder
**Before:**
**After:**
> Subscribe to Newsletter Buttons Alignment Fixed

- index.html
- style.css
Applied styling on social media Icons and changed social media icons with a hover effect
- change the style of social media 
- change the animation style of Social media icons
fix issue #46
> Improve Social Media Icon Design and added animation.

- index.html
- style.css
i fixed the navbar and the hero image positioning
resolving #2 
this is how it is 
these are the changes i made
> adding navbar feature

- index.html
- style.css
I have added copyright information to the footer.
> Adding Copyright Information to the Footer.

- index.html
- style.css
Reverts Tejashri-Taral/TrendTrove-Ecommerce#107
> Revert "Fixed the appearance and response of nav bar"

- features.html
- index.html
- styles.css
#108 fixed @Tejashri-Taral 
I add the fetures page to the website 
add gssoc-ext,hactoberfast accepted and level 2 label 
Screenrecording
https://github.com/user-attachments/assets/92c41be0-5571-4cfb-91d2-c85faa37553f
#108 fixed
> Add Features page to the website

- index.html
- style.css
https://github.com/user-attachments/assets/daedae8a-0ae4-405f-869d-7719d5fbba36
closes #179
> Added a Scroll "Progress Indicator Bar"

- style.css
- Added the animations to the buttons on hover and 
- removed the hyperlink on the shop sneakers button
- issue #94
> Added the animations to the buttons #94

- faq.html
- index.html
#132 add FAQ section in Quick links. 
I have added FAQ section as per the home page layout.
image after adding it:
Thank you.
> added FAQ section in quick links at footer

- index.html
- mens.html
- style.css
- womens.html
Closes: Issue #28 
Title: add scroll to top button
Your Name: Shrishti Singh
Idenitfy yourself: Contributor in gssoc-ext and Hacktoberfest
Describe the add-ons or changes you've made 📃
Give a clear description of what have you added or modifications made
I have added the "scroll to top" button to the application. This feature will enhance user navigation, especially on pages with long content, allowing users to easily return to the top without manually scrolling.
> conflicts resolved and issue resolved #28

- mens.html
- style.css
- womens.html
pull request:
issueno:#214 closes
I have added the add-to-cart button to every product in men,women section and added some hover effect to button and styled it.
https://github.com/user-attachments/assets/cb287e85-5502-49f1-aa1b-124f3205ef69
https://github.com/user-attachments/assets/c6840330-4ee5-44b8-a1b4-4127d823ea8d
> added add-to-cart button to mens,women page

- login-sginup.html
issue num #300 
The input box color was not changing when it was active, so I changed it to improve user interaction.
Added CSS rules to change the color of the input box when it is focused (active).
Before 
After
> Changes colour of input box when it is active

- mens.html
- style.css
- womens.html
i have created the navbar as the home page have.
the issue #64 i have created last week for the makeover of product page then i couldn't work for personal reasons and i saw the website yesterday and the product page is developed but i want to work on this project so i found an feature issue that was in the mens and womens navbar section the navbar was not same as the homepage of the website so i have created that in both sections.
**before**
**After**
please merge this PR under gssoc - hacktoberfest and close the issue #64.
> made the navbar same as home page

- mens.html
issue num #216 
enhanced all the men's products into more attractive for users
also added background color for headings-top wear, bottom wear
https://github.com/user-attachments/assets/263c3052-8761-432f-8ecd-899d7f73b4f6
> ALIGNMENT and ENHANCEMENT of all men products

- about.html
- contact.html
- index.html
- sneaker.html
- style.css
- styles.css
#220 Fixes
fix the scrolling behavior to smooth along with remove unnecessary # link from product that makes an extra link.
And also fixed the color issue related to product nav link on various pages. by adding some extra css
https://github.com/user-attachments/assets/28a81142-8e9e-4079-a183-17f3ac405e3b
> [BUG] Smooth Scrolling and Product Nav link fix

- about.html
- contact.html
- features.html
- index.html
I have corrected the spelling mistakes under the Products tab, from Mens and Womens to Men and Women across each tab.
> Navbar changes under Products Tab

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> [Feat] Bug & Feature Preset Added

- return-policy.html
BUG:navbar links not working in return policy page #272
> navbar updated in return policy page

- products/bags.html
- products/productscss.css
- products/sandals.html
- products/sunglasses.html
> navbar integrated successfully in product pages

- .github/ISSUE_TEMPLATE/greetings.yml
- .github/ISSUE_TEMPLATE/pr-comment.yml
fixes : #30
now it automates the greetings when ever an issue is raised or pullrequest  is opened
> added the github greeting bot 

- contact.html
- style.css
Updated the contact page for #164 . Can you please verify it
> Contact page update

- .vscode/settings.json
- about.html
- contact.html
- return-policy.html
- terms-conditions.html
I have added the Social media handel's (like LinkedIn, GitHub, Twitter, Instagram) in all the footer sections.
please merge my pull request @Tejashri-Taral .
> Adding the Social Media in all the footer Section.

- index.html
- style.css
I have changed the color of heart when hovered from white to a variant of red - rgb(255, 84, 84) from all the sections in website.
Issue Number- #377 
<h2>Fixed Screenshot</h2>
<h4>Heart when hovered:</h4>
> #377 Fixed heart hover

- Boy.html
- about.html
- child.html
- contact.html
- features.html
- index.html
- login-sginup.html
- mens.html
- preloader.js
- preloaderStyle.css
- womens.html
Issue Fixed: #237 
Styling has been applied to the preloader and scroll bar. The preloader and Scroll bar is present on all pages of the website with styling. The scroll bar behaviour has been improved and the thumb and track have been redesigned, resulting in improved scroll behaviour.
*Improvements:*
1. *Optimized Preloader:* Enhanced the preloader animation on the landing, Boy, about, child, contact, features, login-signup, mens, and womens pages to improve user experience.
2. *Revamped Preloader Design:* Redesigned the preloader with modern CSS styling to enhance visual appeal.
3. *Dedicated Preloader Script and StyleSheet:* Created a separate JavaScript file named `"preloader.js"` to manage the preloader functionality and CSS file named `" preloaderStyle.css"` to enhance the styling …
> improve scroll bar and preloader

- mens.html
I have corrected the alignment of all the products in the mens section 
Issue resolved: #386
Please label it as level 2 if possible.
> alignment corrected

- .github/workflows/autocomment-issuecreation.yml
Made the code changes to create a bot which automatically comments on a new issue created. Would like to work on more creation of bots.
Solved : #467
> Created bot for new issue creation

- about.html
hover effect added to photos of about
>  enhanced design

- about.html
Reverts Tejashri-Taral/TrendTrove-Ecommerce#540
> Revert "Rectified the bug as there is a presence of the quick links twice"

- about.html
- contact.html
- features.html
I've created a scroll back button to all the pages 
issue. no. : #558 
https://github.com/user-attachments/assets/ae95f997-4fe3-4d9b-af9c-b44284f1ba97
> Added Scroll-back button to all the pages

- shopclothing.html
https://github.com/user-attachments/assets/ba6c0104-1721-4b8b-9419-29ec9d117228
In the Shop clothing Section now the size filter is working.
please merge it @Tejashri-Taral and add the label.
> Size filter is working in Shop clothing Section

- index.html
- login-sginup.html
This pull request addresses issue #521 by adding anchor tags for the Terms of Service and Privacy Policy on the login-signup page. The following changes were made:
#Added anchor tags linking to the Terms and Privacy Policy pages.
#Updated the href from # to terms-conditions.html to ensure proper navigation.
These changes enhance user experience by providing clear access to important policy information during the signup process.
- fixes - #521 
BUG :
RESOLVED :
> Fix: Update Links for Terms and Privacy in Login-Signup Page

- index.html
- style.css
Description: Here I fixed the issue in The " Shop From Gram section" the posts are not have their aspect ratio correctly managed, It was viewing like stretched and The Feedback options have not looks visually appealing with its fonts, I fixed both the issues for various screen sizes.
Before Changes: 
After Changes:
I have added more effects on hovering on feedback click here and the instagram logo in the cards.
Hope you like my work!
> "Shop From The Gram" the card and its images  resizing issue fixed

- index.html
- login-sginup.html
- privacy.html
This pull request addresses issue #547 by adding a new Privacy Policy page to the website. 
The following changes were made: 
- Created a new Privacy Policy page with relevant content.
- Linked the Privacy Policy page on the login/signup page and in the pop-up for easy access.
These changes improve user awareness of privacy practices and ensure compliance with user data regulations.
This is the new Privacy Policy page i made for this website , i have made sure to link this page on login/signup page 
as well as the pop-up
- issue #547
> Add Privacy Page and Link in Index/Login/Signup

- README.md
- contributors.css
- contributors.html
- contributors.js
Updated the readme file with the featured in, repo review table and our contributors
closes :- #346 
@Tejashri-Taral Please review this PR and merge it and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level.
> Updated the readme file with the featured in, repo review table and our contributors

- contributors.css
- contributors.html
- contributors.js
Added the contributors page to the website with sleek ui, matching the theme of the website, integrated footer and navbar in it, fully responsive over all screen sizes, dynamic ui updates as the new contributors are added the repository and best practices while coding.
So i think it deserves a level 3 for my efforts on this page.
closes :- #343 
https://github.com/user-attachments/assets/ea574347-dc48-40b2-887f-df944f4fd7bb
https://github.com/user-attachments/assets/55892d98-20c8-4512-be7f-abd321dbd044
@Tejashri-Taral Please check this PR and merge it and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level.
> Added the contributors page

- contact.html
- style.css
https://github.com/user-attachments/assets/13c285a7-12f2-4ddc-a09a-22a7775c4956
> add tooltips on the contact form

- contact.html
- style.css
Map in Contact page now responsive #433 
https://github.com/user-attachments/assets/b71bb81d-e165-4a7f-8d8f-52090b9dd083
> Map in Contact page now responsive

- Style/about.css
- about.html
- contact.html
- features.html
- feedback.html
- index.html
- mens.html
- script/modal_box.js
- sneaker.html
- terms-conditions.html
- womens.html
> #534 Issue Solved - Added Translator Tool

- about.html
- contact.html
- products/bags.html
- products/sandals.html
- products/sunglasses.html
- return-policy.html
- shopclothing.html
- sneaker.html
This pull request adds a login link to the navigation menu on the About and Contact pages of the TendTrove website. 
- Updated about.html to include a login link in the navigation section.
- Updated contact.html to include a login link in the navigation section.
The addition of the login link enhances the user experience by providing easy access to the login functionality from all pages, allowing users to navigate to their accounts quickly.
Please review the changes and let me know if any further modifications are needed.
> Add login link to navigation in all  required pages

- styles.css
https://github.com/user-attachments/assets/45998b57-9edc-437b-b340-e5ed8222f8e3
please take a look i have changed the UI of feature section.
> I have changed the UI section of feature section.

- about.html
hey @Tejashri-Taral ,I have fixed the bug .
closes #602 
**Before**
**After**
Make sure to add levels(level1,level2,level3)
> blog page bug it fixed

- login-sginup.html
added google and facbook ,x button in login page An easy-to-find close button helps users exit unwanted content, improving satisfaction and reducing frustration.
https://github.com/user-attachments/assets/27a6d787-da2f-43f2-9353-244780bf4a29
fix    #636
> added button google facbook and X

- index.html
- shopclothing.html
- sneaker.html
- style.css
**Could you please add level tag.......** @hars-21 
BEFORE:
AFTER:
> Adjusted Filter Box Sizes for Better UI

- Boy.html
- Style/about.css
- Style/bags.css
- Style/sandals.css
- Style/sneaker.css
- Style/sunglasses.css
- about.html
- accessories.html
- cart.html
- child.html
- contact.html
- contributors.css
- contributors.html
- faq.html
- features.html
- index.html
- login-sginup.html
- mens.html
- privacy.html
- products/productscss.css
- return-policy.html
- script/progressbar.js
- shopclothing.html
- sneaker.html
- style.css
- styles.css
- terms-conditions.html
- womens.html
Hi @Tejashri-Taral 
issue closes #670 
i have added the scroll progress bar
please review it under hactoberfest'24.
> ✔️Added Scroll Progress bar into the website

- feedback.html
- index.html
**[Feat]: Designing Feedback Form Page and Adding Navbar and Footer to It**
**Description**
This pull request implements a feedback form page with a clean and responsive design. It includes the following enhancements:
**Feedback Form Design**: Created a user-friendly feedback form that captures user inputs such as name, email, satisfaction ratings, and suggestions. The form is styled with Bootstrap for responsiveness and aesthetics.
**Navbar Addition:** Integrated a navigation bar at the top of the page for easy access to other sections of the website, improving overall user experience.
**Footer Addition:** Added a footer containing copyright information and links to social media, enhancing the page's professionalism and providing additional navigation options.
**Features**
- Responsive …
> solve [Feat]: Designing Feedback Form Page and Adding Navbar and Footer to It #639

- faq.html
AFTER:
@Tejashri-Taral  @hars-21
> Extended FAQs Section for Improved Buyer Communication

- features.html
#129 PR , add features page to the website , In leaderboard my this #129 pr points is not showing so please review it and merge my PR , Add Gssoc-ext , Hactoberfest accepted and level 2 to this issue , currently I need points on the leaderboard , It would be very helpful for me @Tejashri-Taral . 
I only changes the text so by merging this PR , nothing change to website😊
> features page added

- accessories.html
- style.css
Fixed Issue #508 
This pull request aims to enhance the user experience on the Accessories page by refining the hover effect on product cards. The goal is to create a more visually appealing and interactive experience for users.
- **Modified CSS:** Adjusted CSS styles to modify the hover effect on product cards.
- **Enhanced Visual Appeal:** Increased the intensity of the hover effect, making it more noticeable and engaging.
- **Improved Responsiveness:** Ensured the hover effect functions seamlessly across different screen sizes and devices.
- Thoroughly tested the hover effect on various devices and on chrome browsers to ensure consistent behavior.
- Verified that the changes do not negatively impact the overall page layout or performance. …
> Improve Hover Effect on Accessories Page Cards

- index.html
- script/progressbar.js
- style.css
I saw how you created a script file for progress bar so in that I just added few more lines of code to fix the navbar and some css . Because of this user will be able to navigate more easily . 
Fixes #614
> Navbar fixed on top.

- accessories.html
- mens.html
- script/share-button.js
- style.css
- womens.html
the share container's position is fixed and it isn't glitching anymore on the hero section. the changes made are responsive with respect to the screen sizes as well.
https://github.com/user-attachments/assets/736b6ab9-3af0-41d2-a048-c663d6d60685
@Tejashri-Taral please add the labels , thanks :) ( i hope the changes made are fine with you )
closes #660
> solved #660 fixed glitching share box on hero section 

- accessories.html
- style.css
#580
https://github.com/user-attachments/assets/f2ed96b8-97bb-4bdb-a4d4-cf0a4f32e12e
fixed the footer 
@Tejashri-Taral
> updated the footer

- cart.html
- womens.html
I made the add to cart button responsive and also the added elements will be displayed in the cart. we can increase and decrease the item count in cart also.
https://github.com/user-attachments/assets/bcf96b91-3754-45a1-aef6-2a1e9f8f8530
I made the changes only for the women section.
> Add to cart functionality

- login-sginup.html
Proper aligning of login ans signup pages which were properly visible on the screen.
Fixes #691
before:
after:
I hope the contribution made was beneficial!
> Proper aligning of login ans signup pages

- Boy.html
- accessories.html
- child.html
- mens.html
- style.css
- styles.css
- womens.html
fix #710 
https://github.com/user-attachments/assets/31c1e7e6-097b-41e3-a02c-ddcb693f7266
> added rating in the product

- Boy.html
- accessories.html
- child.html
- mens.html
- style.css
Issue resolved: #608
BEFORE
AFTER
> Overlapping of content fixed

- return-policy.html
This update enhances the **Return and Refund Policy** section by adding an interactive card layout to improve readability and user experience. Each point of the policy is now enclosed in individual "cards" with hover effects, which adds both structure and a modern touch to the UI. This update ensures that users can easily browse through each policy item and absorb key details in a visually appealing format.
- **Card Layout for Each Policy Point:** Every policy item is wrapped within its own card, providing a structured layout that separates individual sections for better readability.
- **Hover Effects:** Added smooth hover effects to each card, which create a slight elevation and shadow effect, enhancing the user experience and providing visual feedback.
- **Simplified HTML Structure:** …
> Enhance Return and Refund Policy Section with Card Layout and Hover Effects

- index.html
- style.css
Fixes #613 
I made some basic UI fixes that includes: 
1. Scroll Animation 
2. Changed font family on buttons on the feature section 
3. Changed background color to match the grey white theme of the site . 
This is how it looks .
Thank you .
> UI Fixes on the main page .

- about.html
- index.html
- style.css
Fixes: #729 
added toggle button
**### Screenshots / videos (if applicable)**
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
without toggle-
with toggle-
I have provided relevant issue numbers and screenshots after making the changes.
Please add GSSOC EXTD and level labels to the PR
> Added toggle button

- about.html
- index.html
- style.css
Reverts Tejashri-Taral/TrendTrove-Ecommerce#730
> Revert "Added toggle button"

- about.html
- features.html
- index.html
- style.css
- styles.css
I made the following changes to dark mode:
1)I ensured that the footer also changes in dark mode, by restyling it.
2)I ensured that icons, including the logo are also visible in dark mode.
3)previously, when hovering on products, while we are hovering the dropdown the products text is invisible due to conflicting styles.
here's a preview:
https://github.com/user-attachments/assets/5bd338bb-7ee6-482d-8f8f-0aebdf1a591f
@Tejashri-Taral please review my pr..
> fixed dark mode

- about.html
- features.html
- index.html
- style.css
- styles.css
issue no: #761 
1)I added id to feature section and onclick functionality to explore more button to navigate to feature section on click.
here is the preview:
https://github.com/user-attachments/assets/053ccd5e-e7b1-4f2e-aa8a-196bff10ecc8
@harikasayani , please review my pr..
> made explore more interactive

- index.html
https://github.com/user-attachments/assets/156b25fb-2796-4cba-acd7-406fe3390326
added cart button and rating 
fix #743
> added button cart and rating

- index.html
Reverts Tejashri-Taral/TrendTrove-Ecommerce#772
> Revert "added button cart and rating"

- about.html
- features.html
- index.html
- style.css
- styles.css
Reverts Tejashri-Taral/TrendTrove-Ecommerce#766
> Revert "made explore more interactive"

- style.css
> issue number #773 is solved

- cart.html
- index.html
#761 
I have made the following changes:
1)Properly aligned and styled the item details and heading for improved readability.
2)Added a hover effect to the cart items to enhance interactivity.
3)Implemented a dynamic item counter that updates automatically based on the cart contents.
4)Introduced a notification pop-up for item removals to inform users in a subtle, non-intrusive way.
here is a preview:
https://github.com/user-attachments/assets/5460db61-e7e9-46f5-bd2f-dd9aab2bda01
@Tejashri-Taral please review..
> upated cart page

- index.html
- sitemap.html
Fixes:  #715 
This pull request introduces a comprehensive site map for the project. The site map includes links to all relevant pages and resources within the application. This will enhance user navigation and improve search engine optimization (SEO).
**Created a new file**: A new file named `sitemap.html` is created with all the styling. 
The program was tested locally on a machine using the Chrome browser. To verify the changes, the website was loaded after the modifications were made. This involved manually inspecting the visual elements and functionally testing various user interactions to ensure the changes were implemented correctly.
https://github.com/user-attachments/assets/5919c51d-c582-49d2-9880-0ec60e25918d
> Created Site Map Page

- about.html
- styles.css
fixed footer such that it aligned with remaining all the pages footer style
also I've removed the extra scroll to top buttons in the page that make the page good looking!!
@Tejashri-Taral you can check this out!!
> Fixed footer in About page (fixes #735)

- index.html
- style.css
Issue resolved: #744
BEFORE: 
AFTER:
> changed font style in footer

- index.html
- style.css
Reverts Tejashri-Taral/TrendTrove-Ecommerce#798
> Revert "changed font style in footer"

- index.html
fixes: #635 
https://github.com/Tejashri-Taral/TrendTrove-Ecommerce/pull/797
Here's the demo that it's working now:
https://github.com/user-attachments/assets/c4d61aa0-b468-4303-a883-b5c83c2058f0
> Add Hover Effect to Main Heading for Dynamic Appearance

- index.html
Added a feature so that when button toggled dark and light theme appear alternatively.
> Changes made to the dark theme
